### ISSUE TITLE
Unable to run yum update with fedora:latest image

### ISSUE THREAD

**Issue by babelouest** [fedora-cloud/docker-brew-fedora#100]
Hello,

While running fedora:latest instance (`sha256:72c6c48a902baff1ab9948558556ef59e3429c65697287791be3c709738955b3`), I'm unable to use yum update or any other command that wants to access the internet. I get the error `getaddrinfo() thread failed to start`.

```
$ docker run -it --rm fedora:latest bash
Unable to find image 'fedora:latest' locally
latest: Pulling from library/fedora
fc811dadee24: Pull complete 
Digest: sha256:72c6c48a902baff1ab9948558556ef59e3429c65697287791be3c709738955b3
Status: Downloaded newer image for fedora:latest
[root@5b630cab4f42 /]# yum -y update
Fedora 35 - x86_64                                                                                                                                  0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
[root@5b630cab4f42 /]# 
```

The previous fedora version works though.

Is there something missing on my side?

**Comment by bbebse2** [comment]
Same issue here. It seems like the DNS for curl is not working. If you run curl <any url>, you will get "curl: (6) getaddrinfo() thread failed to start". But if you run curl with "--resolve" options, it works fine. Chaning the file /etc/resolv.conf or /etc/hosts will not work. It looks like curl does not using the system DNS config.

**Comment by babelouest** [comment]
The problem seems fixed now, I'm closing this issue then
