### ISSUE TITLE
Rawhide is still fc38

### ISSUE THREAD

**Issue by elmarco** [fedora-cloud/docker-brew-fedora#108]
Can it be switched to fc39?

https://github.com/fedora-cloud/docker-brew-fedora/blob/c1e2120c04b86ae4e73f14806066bca6e6200d9c/x86_64/Dockerfile
```
FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"                    
ENV DISTTAG=f38container FGC=f38 FBR=f38
ADD fedora-38-x86_64.tar.xz / 
CMD ["/bin/bash"]
```
thanks

**Comment by elmarco** [comment]
@cverna

**Comment by cverna** [comment]
Update pending https://github.com/docker-library/official-images/pull/14243
