### ISSUE TITLE
Rawhide docker image needs updating

### ISSUE THREAD

**Issue by ac000** [fedora-cloud/docker-brew-fedora#116]
The current docker Fedora Rawhide image breaks after doing a dnf upgrade (looks like an issue with the move to dnf5)

After the dnf upgrade completes, then when trying to install some packages we gets loads of

```
[  1/251] Installing nodejs-npm-1:10.8. 100% |  99.9 MiB/s |   8.2 MiB |  00m00s
>>> Unpack error: nodejs-npm-1:10.8.1-1.22.3.0.1.fc41.x86_64
[  1/251] Installing glibc-gconv-extra- 100% | 178.8 MiB/s |   7.9 MiB |  00m00s
>>> Unpack error: glibc-gconv-extra-0:2.39.9000-26.fc41.x86_64
[  1/251] Installing python-unversioned 100% | 103.5 KiB/s | 424.0   B |  00m00s
[  2/251] Installing which-0:2.21-41.fc 100% |  80.5 MiB/s |  82.4 KiB |  00m00s
warning: posix.fork(): .fork(), .exec(), .wait() and .redirect2null() are deprecated, use rpm.execute() instead
>>> Unpack error: which-0:2.21-41.fc40.x86_64
warning: posix.wait(): .fork(), .exec(), .wait() and .redirect2null() are deprecated, use rpm.execute() instead
warning: posix.exec(): .fork(), .exec(), .wait() and .redirect2null() are deprecated, use rpm.execute() instead
Transaction failed: Rpm transaction failed.

Error: Process completed with exit code 1.
```

Current Fedora Rawhide (when I tried it the other day) seems OK'ish...

The current docker Rawhide image seems to be two months old...

Did the [weekly](https://github.com/docker-library/official-images/issues/7529) image updating ever happen?

**Comment by cverna** [comment]
Opened a PR to update this https://github.com/docker-library/official-images/pull/17160.

And no the weekly updating never happened :(

**Comment by cverna** [comment]
Small issue with that PR, I need to fix the script that pulls the images from Fedora's infrastructure. Will do that tomorrow.

**Comment by ac000** [comment]
Looks good now, thanks!
