### ISSUE TITLE
Update fedora page on docker hub to latest release

### ISSUE THREAD

**Issue by stefan-it** [fedora-cloud/docker-brew-fedora#13]
Hi,

the description page on [Docker Hub](https://registry.hub.docker.com/_/fedora/) needs also to be updated e.g.:

```text
 Official Fedora 21 base image and semi-official Fedora 20 and rawhide images. 
```

or:

```text
This image serves as the official Fedora image for Fedora 21 and as a semi-official image for Fedora 20 (heisenbug) and rawhide.
```

Because of the Fedora [22](https://github.com/fedora-cloud/docker-brew-fedora/blob/e5a0a567230ca8350d2be9b100604858fc898c0b/Dockerfile) release :)

Thank you :)

**Comment by lsm5** [comment]
this was done few days ago, thanks!
