### ISSUE TITLE
here, have some builds for older fedora versions

### ISSUE THREAD

**Issue by mcandre** [fedora-cloud/docker-brew-fedora#15]
Examples:

https://registry.hub.docker.com/u/mcandre/docker-fedora/tags/manage/

Source:

https://github.com/mcandre/docker-fedora

**Comment by maxamillion** [comment]
There's not any real motivation to ship End-Of-Life'd versions of Fedora in an official capacity as Docker base images. They aren't officially supported by the project anymore and users shouldn't be using them. Why would an user want an old version of Fedora? Am I missing something?

**Comment by mcandre** [comment]
Agreed, using old, unsupported, insecure versions are inadvisable from a good sysadmin position. However, for research, compatibility, or archival reasons, some people may, in fact, want to have easy access to older versions. And more official Docker images is a good way to provide access to old OS's.

**Comment by maxamillion** [comment]
Discussion on this within the Fedora devel community is happening [here](https://lists.fedoraproject.org/pipermail/devel/2015-July/212486.html), please feel free to join the discussion if you are interested.
