### ISSUE TITLE
dnf update fails on fedora:rawhide

### ISSUE THREAD

**Issue by lsm5** [fedora-cloud/docker-brew-fedora#18]
$ sudo docker run -it fedora:rawhide dnf update
    Config error: Can not read configuration: /etc/dnf/dnf.conf

ping @maxamillion, do we need a rel-eng ticket for this, or is it ok to just file issues here? :)

**Comment by lsm5** [comment]
filing rel-eng tickets ain't exactly a joy :) , but I will if needed :)

**Comment by maxamillion** [comment]
To the best of my knowledge this is a bug with using overlayfs as the storage provider. Someone told me it was known upstream and being worked on. I'll follow up and find out where the bug is being tracked.

**Comment by maxamillion** [comment]
@lsm5 - Did you ever get a chance to test this against something other than overlayfs?

**Comment by lsm5** [comment]
hmm, don't see this issue anymore, but iirc, I don't think I was using overlayfs

**Comment by elmarco** [comment]
I use overlayfs, and I can still see this issue.

**Comment by maxamillion** [comment]
To the best of my knowledge it is still an unresolved bug in dnf.

**Comment by elmarco** [comment]
btw, I noticed a selinux error, disabling selinux on host works around it. I have not investigated further.
