### ISSUE TITLE
Fedora 21: /etc/yum.repos.d/*.repo needs to be updated

### ISSUE THREAD

**Issue by stefan-it** [fedora-cloud/docker-brew-fedora#2]
Dear Lokesh,

I'm using the fedora:21 image and wanted to update + install packages via yum. It was not possible as version 21 is not really published on mirrors.

Here is a workaround:

```bash
from fedora:21

run sed -i 's%^#\(baseurl=\).*%\1http://dl.fedoraproject.org/pub/fedora/linux/development/$releasever/$basearch/os/%g' /etc/yum.repos.d/fedora.repo
run sed -i 's/^\(metalink.*\)/#\1/g' /etc/yum.repos.d/fedora.repo
run sed -i 's/^\(gpgcheck=\).*/\10/g' /etc/yum.repos.d/fedora.repo

run sed -i 's%^#\(baseurl=\).*%\1http://dl.fedoraproject.org/pub/fedora/linux/updates/$releasever/$basearch/%g' /etc/yum.repos.d/fedora-updates.repo
run sed -i 's/^\(metalink.*\)/#\1/g' /etc/yum.repos.d/fedora-updates.repo
run sed -i 's/^\(gpgcheck=\).*/\10/g' /etc/yum.repos.d/fedora-updates.repo

run sed -i 's%^#\(baseurl=\).*%\1http://dl.fedoraproject.org/pub/fedora/linux/updates/testing/$releasever/$basearch/%g' /etc/yum.repos.d/fedora-updates-testing.repo
run sed -i 's/^\(metalink.*\)/#\1/g' /etc/yum.repos.d/fedora-updates-testing.repo
run sed -i 's/^\(gpgcheck=\).*/\10/g' /etc/yum.repos.d/fedora-updates-testing.repo

run yum -y clean all
run yum -y update
```

Maybe the development ```baseurl``` can be integrated directly in the ```fedora:21``` image?

Btw: I found the development urls [here](http://fedoraproject.org/wiki/QA/Test_Days/Live_Image) - so hopefully I'm using the right ones ;) ```gpgcheck=0``` is necessary, because of a *rpm is not signed* error message.

Thanks in advance + regards,

Stefan

**Comment by lsm5** [comment]
@stefan-it sorry about the late reply on this, i'm guessing everything's solved in this case, now that f21 is released. Closing this, please let me know if anything's still messed up.
