### ISSUE TITLE
tsflags=nodocs is missing from dnf.conf

### ISSUE THREAD

**Issue by oszi** [fedora-cloud/docker-brew-fedora#20]
Since the switch to DNF `tsflags=nodocs` is still only appended to /etc/yum.conf
(and not /etc/dnf/dnf.conf). So this affects the 22 and rawhide branches here:

```
awk '(NF==0&&!done){print "override_install_langs='$LANG'\ntsflags=nodocs";done=1}{print}' \
    < /etc/yum.conf > /etc/yum.conf.new
mv /etc/yum.conf.new /etc/yum.conf
```

-- Lightning

**Comment by maxamillion** [comment]
Apologies for the terrible lag time on this.

https://git.fedorahosted.org/cgit/spin-kickstarts.git/commit/?id=6ea47a9570c47a318c9942973dd05b3f18f7d0a3

Should be in tonights nightly.
