### ISSUE TITLE
Fedora 23 docker image?

### ISSUE THREAD

**Issue by alanfranz** [fedora-cloud/docker-brew-fedora#22]
Hello,
a docker image is provided for both Fedora 22 and Fedora Rawhide (which is the future Fedora 24 AFAICU), but there seems to be no image for the current Fedora 23 Alpha/Beta/RC, something that would be **very** useful for testing on the next stable Fedora.

Would it be possible to add it?

**Comment by praiskup** [comment]
I am curious too .. but this helped me to create sufficiently new image (import from tar) for now:
http://koji.fedoraproject.org/koji/tasks?state=closed&view=flat&method=createImage&order=-id

**Comment by maxamillion** [comment]
https://github.com/docker-library/official-images/pull/1156
