### ISSUE TITLE
Create Red Hat Bugzilla component for Fedora base images

### ISSUE THREAD

**Issue by praiskup** [fedora-cloud/docker-brew-fedora#23]
ssia

**Comment by praiskup** [comment]
@vpavlin fyi

**Comment by adelton** [comment]
My understanding was that this is *the* place where the base images live and these issues are the right tool to raise issues.

**Comment by praiskup** [comment]
@adelton, not having bugzilla component is inconvenient to me.  Its the first
place I look into when I plan to send a bugreport against Fedora product/component.

I failed to find the fedora-cloud/docker-brew-fedora project to raise an issue,
is this documented somewhere?  I would expect it to be at least on:
https://hub.docker.com/r/fedora/postgresql/

**Comment by adelton** [comment]
> not having bugzilla component is inconvenient to me

Oh, I didn't say this wasn't suboptimal.

**Comment by adelton** [comment]
I assume the answer to this request is https://bugzilla.redhat.com/buglist.cgi?classification=Fedora&product=Fedora%20Container%20Images, is that correct, @cverna?

**Comment by cverna** [comment]
Yes :)
