### ISSUE TITLE
Regression: fedora:22 tag points to Fedora 20 docker image

### ISSUE THREAD

**Issue by adelton** [fedora-cloud/docker-brew-fedora#32]
```
# docker run -ti fedora:22 cat /etc/redhat-release
Fedora release 20 (Heisenbug)
# docker images fedora
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker.io/fedora    22                  0d071bb732e1        4 weeks ago         290.6 MB
```

Things were sane yesterday when fedora:22 was pointing to ded7cd95e059.

Also reported as https://fedorahosted.org/cloud/ticket/137.

**Comment by maxamillion** [comment]
This hasn't changed, please file against the docker-library here: https://github.com/docker-library/official-images

Reference:
https://github.com/docker-library/official-images/blame/master/library/fedora

**Comment by maxamillion** [comment]
I'm following up upstream.
