### ISSUE TITLE
Fedora 24 docker image

### ISSUE THREAD

**Issue by plaperdr** [fedora-cloud/docker-brew-fedora#36]
Hello,
It is maybe a little early but the alpha of Fedora 24 just released today so it would be great to add a Fedora 24 Docker image in the coming weeks.
Thanks in advance,
Pierre

**Comment by joemiller** [comment]
Getting close. It looks like 2016-06-21 is the likely GA release date now.

https://fedoraproject.org/wiki/Releases/24/Schedule
