### ISSUE TITLE
F24 image has only C and POSIX locales

### ISSUE THREAD

**Issue by clime** [fedora-cloud/docker-brew-fedora#39]
F24 image contains only the following locales:

```
[root@a1f27e8300c4 workdir]# locale -a
C
C.utf8
POSIX
```

This comes from the base cloud image. 

There is a typo on this line: https://github.com/fedora-cloud/docker-brew-fedora/blob/24/koji-f24-build-15263133-base.ks#L35

It should say `%_install_langs $LANG` according to https://fedoraproject.org/wiki/Changes/Glibc_locale_subpackaging

It would be nice, however, to enable all locales.

**Comment by praiskup** [comment]
Good catch.  You need to submit the bug against spin-kickstarts, however.

> It would be nice, however, to enable all locales.

This is probably not possible, because we need as small image as possible.

**Comment by siddharthvipul** [comment]
issue related to the EOL versions. Please reopen if you notice this in newer images
