### ISSUE TITLE
Please provide 32 bit docker image

### ISSUE THREAD

**Issue by mdeguzis** [fedora-cloud/docker-brew-fedora#42]
Can you provide a 32 bit docker image?

**Comment by itamarjp** [comment]
I have a similar question about armv7

**Comment by yosifkit** [comment]
@maxamillion, we're finally officializing a lot of the multiarch work we've been doing, and as such we think we've finally got some decent examples that are worth looking at for how Fedora might be enabled for multiarch :slightly_smiling_face:  We also have a [multiarch section](https://github.com/docker-library/official-images/tree/01714aa7a310c8b5f24b3cd45a29e33c1b5d6ee7#multiple-architectures) in the official-images README.md.

https://github.com/docker-library/official-images/pull/3024 (`ubuntu`) and https://github.com/docker-library/official-images/pull/3031 (`debian`) are our first two "base" images with multiarch enabled (no manifest lists yet, just official multiarch specification so we can build/push from a single source of truth -- manifest lists are on the TODO shortly though); @tianon set up https://github.com/tianon/docker-brew-alpine-multiarch as another example of how this could go for Alpine, using the `minirootfs` tarballs that have been officially released (with https://github.com/tianon/docker-brew-alpine-multiarch/blob/master/alpine being an example library file for it).

We are happy to help with any of this! :tada:
