### ISSUE TITLE
Fedora docker image misbehaves in jenkins build pipeline

### ISSUE THREAD

**Issue by dothebart** [fedora-cloud/docker-brew-fedora#43]
Hi, 
I've created this jenkins issue regarding fedora docker image usage over in the Jenkins bug tracker:

https://issues.jenkins-ci.org/browse/JENKINS-39307

Jenkins pipeline scripts will spin up the fedora docker image to do some shell scripts. In the bug report this was reduced to the very minimal: 

    cat /etc/issue; while /bin/true; do echo 'x'; sleep 1; done

which for sure will work in an interactive shell with the docker container, but will abort after the 1st iteration when run via jenkins. To get more facts I've tried older fedora images (yes, they're not supported anymore...) to find out that this miss behavior was introduced from fedora 21->22

Since the docker library only points out to some tarballs, where do I get them? And whats the best way to find out what could be the reason for this behavior?

**Comment by siddharthvipul** [comment]
issue related to the EOL versions. Please reopen if you notice this in newer images

**Comment by dothebart** [comment]
Hi, 
so you close bugreports by solely stating that they're outdated? 
How'bout checking back whether they are fixed?
