### ISSUE TITLE
exit 100 on dnf check-update

### ISSUE THREAD

**Issue by mcandre** [fedora-cloud/docker-brew-fedora#46]
When I try to run `dnf check-update` in fedora:25, it silently fails.

Docker reports a 100 exit status, but other than that, I'm not sure what's going wrong.

FWIW, centos:7, centos:6, and fedora:25 all seem to be having package index updating issues at the moment.

**Comment by siddharthvipul** [comment]
issue related to the EOL versions. Please reopen if you notice this in newer images

**Comment by gusbemacbe** [comment]
Hello @siddharthvipul!

I have still this error on the tag `rawhide`:

* Log

  ```
  #6 ERROR: executor failed running [/bin/bash -o pipefail -c dnf check-update]: exit code: 100
  failed to solve: executor failed running [/bin/bash -o pipefail -c dnf check-update]: exit code: 100
  ```

* `Dockerfile`

  ```dockerfile
  SHELL  ["/bin/bash", "-o", "pipefail", "-c"]
  RUN set -ex && ldconfig
  RUN dnf check-update && dnf upgrade -y
  RUN dnf install -y glibc
  ```

**Comment by gusbemacbe** [comment]
Cc: @cverna
