### ISSUE TITLE
s390x / IBM z Systems support?

### ISSUE THREAD

**Issue by tianon** [fedora-cloud/docker-brew-fedora#48]
Thanks to https://github.com/docker-library/official-images/pull/3176, we now have support for Fedora on several arches including `ppc64le`. :tada:

IBM's pretty keen on adding `s390x` there too -- anything in particular stopping that from happening?  Anything we can do to help make it happen? :smile: :heart:

**Comment by tianon** [comment]
cc @maxamillion @puiterwijk for more visibility :pray:

**Comment by alicefr** [comment]
hi, any updates for this issue?

**Comment by cverna** [comment]
@alicefr we had a few problems with our s390x builder, this should be currently fixed so I ll work on getting a new release out.

**Comment by alicefr** [comment]
ok, if you have any s390x issues please, let me know that we can help

**Comment by cverna** [comment]
I have open a PR to update our images and add s390x for Fedora 28 and Fedora 29.

https://github.com/docker-library/official-images/pull/5040

**Comment by cverna** [comment]
@alicefr the container images are now available on docker hub, could you give it a try ?

**Comment by cverna** [comment]
@alicefr thanks for testing it, I ll ask the docker hub team to check if there is something wrong for f29

**Comment by cverna** [comment]
@alicefr If you don't mind giving another try for f29 that should be working now

**Comment by alicefr** [comment]
it worked now! Thanks to take care of this!

**Comment by cverna** [comment]
Great closing this issue then
