### ISSUE TITLE
document difference on images on hub.docker vs registry.fedoraproject.org

### ISSUE THREAD

**Issue by FlorianLudwig** [fedora-cloud/docker-brew-fedora#51]
Pulling the image `fedora` with the fedora version of docker and the official version does result in different images.

There should be link here to the more up to date registry.fedoraproject.org images.

```
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
registry.fedoraproject.org/fedora   26                  ba857ff07853        2 weeks ago         231MB
fedora                              26                  b0b140824a48        6 weeks ago         231MB
```

**Comment by siddharthvipul** [comment]
this is because of 2 different processes to push images. We now try to keep them as close as possible.
