### ISSUE TITLE
Please update the fedora:26 image to incorporate changes fixing libsolv

### ISSUE THREAD

**Issue by sanseihappa** [fedora-cloud/docker-brew-fedora#52]
Please reference https://bugzilla.redhat.com/show_bug.cgi?id=1483553 and https://bugzilla.redhat.com/show_bug.cgi?id=1394862.

It appears the 2017-09-15 update to the fedora:26 image ends up hampering any "dnf install" commands either during a docker image build or during a docker run.

Is is possible to pick up https://bodhi.fedoraproject.org/updates/FEDORA-2017-9d9767cf8a ?

**Comment by sanseihappa** [comment]
@maxamillion Thank you for incorporating the fix.  I just confirmed the updated fedora:26 image no longer hits the issue that causes "dnf install" to fail (and without having the "dnf -y upgrade libsolve" workaround in place).

**Comment by maxamillion** [comment]
Sorry for not updating the ticket, I completely forgot. Glad things are working out!
