### ISSUE TITLE
dnf unable to update on docker arm32v7/fedora:28

### ISSUE THREAD

**Issue by GeoffClements** [fedora-cloud/docker-brew-fedora#57]
[root@d0f1f115730d dnf]# dnf upgrade --verbose
DNF version: 2.7.5
cachedir: /var/cache/dnf
Cannot download 'https://mirrors.fedoraproject.org/metalink?repo=updates-released-f28&arch=arm': Cannot prepare internal mirrorlist: file "repomd.xml" was not found in metalink.
Error: Failed to synchronize cache for repo 'updates'

**Comment by siddharthvipul** [comment]
issue related to the EOL versions. Please reopen if you notice this in newer images
