### ISSUE TITLE
coreutils conflict on F29

### ISSUE THREAD

**Issue by jborean93** [fedora-cloud/docker-brew-fedora#58]
When trying to install any environment group through dnf I get the following error;

```
[root@fc6dee214c03 /]# dnf upgrade -y
...
[root@fc6dee214c03 /]# dnf install '@Web Server'
Last metadata expiration check: 0:02:06 ago on Wed 31 Oct 2018 01:53:07 AM UTC.
No match for group package "powerpc-utils"
No match for group package "lsvpd"
Error: 
 Problem: problem with installed package coreutils-single-8.30-5.fc29.x86_64
  - package coreutils-8.30-4.fc29.x86_64 conflicts with coreutils-single provided by coreutils-single-8.30-5.fc29.x86_64
  - package coreutils-8.30-4.fc29.x86_64 conflicts with coreutils-single provided by coreutils-single-8.30-4.fc29.x86_64
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
```

Before I do `dnf upgrade` coreutils-single is installed at `8.30-4.fc29` and the upgrade will install `8.30-5.fc29` but the issue really seems to be a conflict between `coreutils-single` and `coreutils` that `@Web Server` expects. This occurs for all other environment groups, `@Web Server` is just an example.

For some background to this, Ansible run's it integration tests for Fedora on Docker containers and the test that is failing is one that tests the dnf module against an environment group install. Currently we only test against F24 and F25 due to other issues but we are trying to upgrade to F28 and F29. Technically I can install this on the F28 container but it does display a message around the coreutils conflicts (even without a dnf upgrade), it just allows me to continue.

Happy to supply whatever you need to debug this further.

**Comment by dustymabe** [comment]
@cverna - can you take a look at this?

**Comment by dustymabe** [comment]
looks like this was done in https://pagure.io/fedora-kickstarts/c/cd0ff18d9739f210acde6667c7d33be078f13f9e?branch=master

cc @james-antill

**Comment by james-antill** [comment]
Yeh, this is a known "feature" of coreutils-single  ... coreutils itself has a bunch of extra deps. (that people wanted to get rid of for the cloud/minimal images) and the maintainer decided to go the way of having the -single package and conflicting. As the error says doing "dnf install --allowerasing coreutils" will fix it.

**Comment by jborean93** [comment]
What are the benefits of `coreutils-single` over `coreutils`, is it just a size difference or other reasons?

**Comment by james-antill** [comment]
I wasn't part of the original arguments/discussions about it ... but yeh, AIUI, the coreutils-single package is just a subset of the coreutils package to lower the dependencies for smaller images.

**Comment by cverna** [comment]
Does this happen only when you do a `dnf update` in the container ? I believe this is not a best practice with containers.

**Comment by dustymabe** [comment]
> Does this happen only when you do a `dnf update` in the container ? I believe this is not a best practice with containers.

could happen when you dnf update or when you install a package that has a dependency on coreutils. It's definitely good to get this fixed. @cverna could you open a PR to the kickstart ?

**Comment by cverna** [comment]
I have opened : 

https://pagure.io/fedora-kickstarts/pull-request/462
https://pagure.io/fedora-kickstarts/pull-request/463
https://pagure.io/fedora-kickstarts/pull-request/465

Once merged and composed I ll ask releng to release the images

**Comment by cverna** [comment]
I have opened https://github.com/docker-library/official-images/pull/5040 to update the images on dockerhub

**Comment by cverna** [comment]
This is now fixed :fireworks:
