### ISSUE TITLE
Time zone should be set to UTC

### ISSUE THREAD

**Issue by vaijab** [fedora-cloud/docker-brew-fedora#6]
Not sure why the time zone is set to America/New_York by default at https://github.com/fedora-cloud/docker-brew-fedora/blob/master/fedora-docker-base-59e73c1.ks ?

I got caught by that which was totally unexpected.

**Comment by vaijab** [comment]
I believe this is being fixed somewhere else.

**Comment by lsm5** [comment]
Yup, fixed [here](https://git.fedorahosted.org/cgit/spin-kickstarts.git/commit/?id=6bf1907a10d764bd7dd1948d84dc6861b74ddc06) ... have [filed a ticket](https://fedorahosted.org/rel-eng/ticket/6098) with fedora rel-eng to spin up a new build

**Comment by lsm5** [comment]
@vaijab do feel free to make some noise over on the rel-eng ticket, more attention it gets, the better :) ... coz fedora rel-eng is where things will happen first and then they'll be propagated over here :|

**Comment by vaijab** [comment]
> do feel free to make some noise over on the rel-eng ticket

Will do. Thanks!

**Comment by thaJeztah** [comment]
@larsks is this the reason the official image on docker hub (https://registry.hub.docker.com/u/library/fedora/) is behind the current master here?
