### ISSUE TITLE
No fedora:30 image for ppc64le platform

### ISSUE THREAD

**Issue by mkumatag** [fedora-cloud/docker-brew-fedora#67]
I don't see fedora:30 for ppc64le platform:

```shell
╰─$ docker manifest inspect fedora:30
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 529,
         "digest": "sha256:09bcfdcd46c3c5b10d6ae182603189a1b7e20db59676d787dad64046fafd961b",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 529,
         "digest": "sha256:15e2256b9d61ef006a9279356a3d910d515372320ad2be49dde11debeb5ebead",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
╭─manjunath@Manjunaths-MacBook-Pro ~
╰─$ docker manifest inspect ppc64le/fedora:30
no such manifest: docker.io/ppc64le/fedora:30
╭─manjunath@Manjunaths-MacBook-Pro ~
╰─$
```

**Comment by mkumatag** [comment]
I see fedora build is failing for ppc64le, not sure whether this has any impact for this!

https://koji.fedoraproject.org/koji/taskinfo?taskID=33082072

**Comment by cverna** [comment]
> I see fedora build is failing for ppc64le, not sure whether this has any impact for this!
> 
> https://koji.fedoraproject.org/koji/taskinfo?taskID=33082072

It does if the rootfs build fails we don't have anything to release :-), I am not sure why it is failing (https://koji.fedoraproject.org/koji/taskinfo?taskID=33082085) and the screenshot does not seems very helpful neither

https://kojipkgs.fedoraproject.org//work/tasks/2085/33082085/screenshot.ppm

**Comment by cverna** [comment]
Ok this might be related to this https://pagure.io/fedora-infrastructure/issue/7598

**Comment by mkumatag** [comment]
> Ok this might be related to this https://pagure.io/fedora-infrastructure/issue/7598

okay, hope will get resolved soon :)

**Comment by cverna** [comment]
> > Ok this might be related to this https://pagure.io/fedora-infrastructure/issue/7598
> 
> okay, hope will get resolved soon :)

We are just before the f30 beta so it is kind of expected for a few things to be on fire :smile:

**Comment by cverna** [comment]
So the issue comes from https://bugzilla.redhat.com/show_bug.cgi?id=1676475

**Comment by cverna** [comment]
https://github.com/docker-library/official-images/pull/5673 fixes this issue.
