### ISSUE TITLE
Fedora 30 is released but latest tag points to 29

### ISSUE THREAD

**Issue by tyll** [fedora-cloud/docker-brew-fedora#69]
https://hub.docker.com/_/fedora says Fedora 29 is tagged as latest but Fedora 30 is already released.

**Comment by cverna** [comment]
We did not have a valid compose since f30 was released so I cannot update the images yet.

**Comment by tflink** [comment]
Is this still the case? 29 is still tagged as latest

**Comment by mohanboddu** [comment]
Yes we were of armhfp issue but s390x is also failing.

@cverna We should dig into this asap.

**Comment by cverna** [comment]
For the time being I opened this to just move the label and use the pre release Fedora 30 images --> https://github.com/docker-library/official-images/pull/6032

**Comment by cverna** [comment]
This is now fixed
