### ISSUE TITLE
Please update the docker image of F31

### ISSUE THREAD

**Issue by kuboosoft** [fedora-cloud/docker-brew-fedora#70]
Hi. Recently, I found  the current image of F31 pointing to rawhide; changing to F32;  the image is mixing criticals f32 packages with F31. Also the GPG keys in F31 is outdated...

Here the reports...

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/7YT4D7GAVTMF3QUDJDUVM5C2HXEJGZGM/

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/RJ66E6WDFCTJDWZMJF4P6W5LXKTOS3VK/

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/TNH7RJCWIILV5VYT3N3IA3VZQIOFNZ53/

**Comment by cverna** [comment]
Hi thanks for the report. The compose of the rawhide and f31 image is currently failing until we have a valid compose we cannot publish a new image.

I am currently working on trying to get a working compose

**Comment by cverna** [comment]
This is done now.
