### ISSUE TITLE
GPG keys broken in fedora:31 image

### ISSUE THREAD

**Issue by ooxi** [fedora-cloud/docker-brew-fedora#71]
Installing any package results in a failure similar to

```
The GPG keys listed for the "Fedora - Rawhide - Developmental packages for the next Fedora release" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: glibc-locale-source-2.30.9000-1.fc32.x86_64
```

Moreover I'm wondering why the message is talking about Rawhide, since I'm pulling `fedora:31`. Maybe this bug is related to issue #70.

**Comment by cverna** [comment]
This should be fixed now

**Comment by ooxi** [comment]
I can confirm that the updated `fedora:31` do no longer have the problem mentioned above.

Thank you @cverna!
