### ISSUE TITLE
useradd behavior changed

### ISSUE THREAD

**Issue by BoleynSu** [fedora-cloud/docker-brew-fedora#80]
After `useradd -r user`, user's uid used to be 999 but is 995 now.

**Comment by cverna** [comment]
@BoleynSu which Fedora version are you using ?

**Comment by BoleynSu** [comment]
```diff
-FROM fedora@sha256:d6a6d60fda1b22b6d5fe3c3b2abe2554b60432b7b215adc11a2b5fae16f50188
+FROM fedora@sha256:93b99d8dbb27450b6848d17669cce2bfe871bcd7534fc3a2bb8bd83c0f026ba1
```
This is the change that changed the useradd behavior.

I checked that f33 works, however, it would be great if f32 can be fixed.

**Comment by BoleynSu** [comment]
Already fixed in new releases.
