### ISSUE TITLE
autoconf not working in rawhide

### ISSUE THREAD

**Issue by tschoonj** [fedora-cloud/docker-brew-fedora#84]
Hi all,

I tried using `fedora:rawhide` as part of a Github Actions CI workflow for my GNU Autotools based project and ran immediately into trouble:

```
autoreconf -fi
41
/usr/bin/autoconf: This script requires a shell more modern than all
42
/usr/bin/autoconf: the shells that I found on your system.
43
/usr/bin/autoconf: Please tell bug-autoconf@gnu.org about your system,
44
/usr/bin/autoconf: including any error possibly output before this
45
/usr/bin/autoconf: message. Then install a modern shell, or manually run
46
/usr/bin/autoconf: the script under such a shell if you do have one.
47
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

The same command works fine on `fedora:latest` as well as on `centos:7` and `centos:8`.

Any thoughts on why this happened? Is there some new exotic default shell in rawhide??

**Comment by dHannasch** [comment]
`fedora:rawhide` cannot be used by GitLab-Runner either.

```yml
test-fedora:
  image: fedora:rawhide
  tags:
  - docker
  script:
  - echo success
```
yields a `shell not found` error. Perhaps GitLab-Runner and GitHub Actions are running into the same kind of problem?

**Comment by pevik** [comment]
Fedora rawhide has problems seccomp() issue with faccessat2() due use glibc 2.33 (the same has openSUSE Tumbleweed and Arch, which also use glibc 2.33):
https://github.com/opencontainers/runc/pull/2750
https://github.com/seccomp/libseccomp/issues/314
I've sent a workaround to glibc: http://patchwork.ozlabs.org/project/glibc/patch/20210225194702.6113-1-pvorel@suse.cz/
