### ISSUE TITLE
Fedora 34 Beta WSL image release

### ISSUE THREAD

**Issue by chadbrewbaker** [fedora-cloud/docker-brew-fedora#87]
https://fedoramagazine.org/announcing-the-release-of-fedora-34-beta/ needs a WSL image.

This article discusses how to build one https://fedoramagazine.org/wsl-fedora-33/

Happy to help. https://github.com/fedora-cloud/docker-brew-fedora/blob/843fecc7a03b3164515d462156d7da597899fe10/x86_64/Dockerfile seems to be a 34 base image. 

I couldn't find it in Koji.

**Comment by cverna** [comment]
The container base image are available here in koji --> https://koji.fedoraproject.org/koji/packageinfo?packageID=26387

We are using the following cli to fetch these builds and prepare them to be pushed on DockerHub (https://github.com/fedora-cloud/fedora-container-release)

**Comment by cverna** [comment]
Going to close this issue, thanks :)
