### ISSUE TITLE
no man pages

### ISSUE THREAD

**Issue by ghost** [fedora-cloud/docker-brew-fedora#9]
Steps to reproduce:

<pre>
$ docker run -t -i fedora:21 bash
# yum provides /usr/share/man/man1/ls.1.gz
fedora/21/x86_64/filelists_db                                                                                                                                           |  25 MB  00:00:01     
updates/21/x86_64/filelists_db                                                                                                                                          |  13 MB  00:00:00     
coreutils-8.22-19.fc21.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : fedora
Matched from:
Filename    : /usr/share/man/man1/ls.1.gz
coreutils-8.22-19.fc21.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : @anaconda
Matched from:
Filename    : /usr/share/man/man1/ls.1.gz
# yum install coreutils
Package coreutils-8.22-19.fc21.x86_64 already installed and latest version
Nothing to do
# ls -l /usr/share/man/man1/ls.1.gz
ls: cannot access /usr/share/man/man1/ls.1.gz: No such file or directory
# yum install man
# man ls
No manual entry for ls
</pre>

(I would happily file a bugzilla bug instead but I got lost trying to see the list of bugs and at the moment I tried the server took about 5 seconds to display a single page)

**Comment by lsm5** [comment]
On Sat, Apr 11, 2015 at 03:32:34AM -0700, Loic Dachary wrote:
> Steps to reproduce:
> <pre>
> $ docker run -t -i fedora:21 bash
> # yum provides /usr/share/man/man1/ls.1.gz
> fedora/21/x86_64/filelists_db                                                                                                                                           |  25 MB  00:00:01     
> updates/21/x86_64/filelists_db                                                                                                                                          |  13 MB  00:00:00     
> coreutils-8.22-19.fc21.x86_64 : A set of basic GNU tools commonly used in shell scripts
> Repo        : fedora
> Matched from:
> Filename    : /usr/share/man/man1/ls.1.gz
> coreutils-8.22-19.fc21.x86_64 : A set of basic GNU tools commonly used in shell scripts
> Repo        : @anaconda
> Matched from:
> Filename    : /usr/share/man/man1/ls.1.gz
> # yum install coreutils
> Package coreutils-8.22-19.fc21.x86_64 already installed and latest version
> Nothing to do
> # ls -l /usr/share/man/man1/ls.1.gz
> ls: cannot access /usr/share/man/man1/ls.1.gz: No such file or directory
> # yum install man
> # man ls
> No manual entry for ls
> </pre>
> 
> 
> 
> 
> (I would happily file a bugzilla bug instead but I got lost trying to see the list of bugs and at the moment I tried the server took about 5 seconds to display a single page)

Yes, I can see this issue too, but this does not occur on the fedora:20 or
fedora:rawhide images.

I would suggest adding a comment about this to the rel-eng ticket here:
https://fedorahosted.org/rel-eng/ticket/6098 . Or perhaps file a new ticket
about this issue.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/fedora-cloud/docker-brew-fedora/issues/9

-- 
Lokesh
Freenode, OFTC: lsm5
GPG: 0xC7C3A0DD

**Comment by dachary** [comment]
Done ! https://fedorahosted.org/rel-eng/ticket/6145

**Comment by rkitover** [comment]
This is really annoying, what is the way to override this setting in the fedora27 image and reinstall all missing man pages?

**Comment by lsm5** [comment]
@maxamillion ^

**Comment by maxamillion** [comment]
The lack of man pages (or any docs at all) is on purpose and has been a topic of debate for a while now, basically it's a question of "do we increase this container image size by a couple hundred  MiB or just live without docs inside the image? Normally the space savings wins in a vote from the [Fedora Atomic WG](https://pagure.io/atomic-wg) It's all controlled from here https://pagure.io/fedora-kickstarts/blob/master/f/fedora-docker-base-minimal.ks

**Comment by rkitover** [comment]
@maxamillion I totally understand why you would not want these things in images that are used as a basis for docker apps, but for those of us using docker as a shell this is very annoying (and there are more of us than you would think.)

My question was just if there was a way to turn it off in the already made images for `dnf`, something simpler than reinstalling packages with `rpm`, reinstalling packages with `dnf` after a config change would be good enough.

**Comment by praiskup** [comment]
@rkitover you want to have a look at `fedora-kickstarts` project to see how the base images are created.... It seems like you are asking for `/etc/dnf/dnf.conf` edit (drop the `tsflags=nodocs`) and reinstall the packages by `dnf reinstall`.

**Comment by rkitover** [comment]
@praiskup Can't believe I missed that, works, thank you very much!

**Comment by gombosg** [comment]
Heck yes!
Workaround solution for later reference: comment `tsflags=nodocs` in `/etc/dnf/dnf.conf`, then reinstall _everything_ with `sudo dnf reinstall $(sudo dnf list --installed | awk '{print $1})`.

I'm going to drop an email to the Fedora Cloud SIG mailing list to see if this can be documented somehow.
