### ISSUE TITLE
 Fedora:34 image missing for ppc64le

### ISSUE THREAD

**Issue by alunsin** [fedora-cloud/docker-brew-fedora#94]
Hi all,

I noticed that the Fedora image is missing for ppc64le.
I also found this [PR 10053](https://github.com/docker-library/official-images/pull/10053)  from @cverna where this image get removed because of an image compose failure.
Is this still failing? FYI I could find some ppc64le image on koji such as the  [build 1745569 ](https://koji.fedoraproject.org/koji/buildinfo?buildID=1745569).
Could we possibly get a refresh for ppc64le image? 

Thanks in advance, 
Aurelien

CC @clnperez

**Comment by cverna** [comment]
This should be now fixed, can you confirm it ?

**Comment by alunsin** [comment]
This working now, thank you @cverna
