### ISSUE TITLE
Docker hub page uses old logo

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-cloud/docker-brew-fedora#99]
Hiya,

Just noticed that the Docker hub page still uses the old logo. Would someone be able to update that please?

https://hub.docker.com/_/fedora

**Comment by sanjayankur31** [comment]
Also filed a ticket with the Mindshare team:

https://pagure.io/mindshare/issue/295

**Comment by cverna** [comment]
Should be fixed by https://github.com/docker-library/docs/pull/2037
